{%- macro common_sports_info_solutions_columns_extraction_list() -%}

            'FB%1',
            'SL%',
            'CT%',
            'CB%',
            'CH%',
            'SF%',
            'KN%',
            'XX%',
            'PO%',
            'FBv',
            'SLv',
            'CTv',
            'CBv',
            'CHv',
            'SFv',
            'KNv',
            'wFB',
            'wSL',
            'wCT',
            'wCB',
            'wCH',
            'wSF',
            'wKN',
            'wFB/C',
            'wSL/C',
            'wCT/C',
            'wCB/C',
            'wCH/C',
            'wSF/C',
            'wKN/C',
            'Swing%',
            'O-Swing%',
            'Z-Swing%',
            'Contact%',
            'O-Contact%',
            'Z-Contact%',
            'Zone%',
            'F-Strike%',
            'SwStr%',
            'CStr%',
            'C+SwStr%',

{%- endmacro -%}