{%- macro common_batted_ball_columns_extraction_list() -%}

            'GB',
            'FB',
            'LD',
            'IFFB',
            'IFH',
            'BU',
            'BUH',
            'Pull',
            'Cent',
            'Oppo',
            'Soft',
            'Med',
            'Hard',
            'bipCount',
            'BABIP',
            'Balls',
            'Strikes',
            'Pitches',
            'GB/FB',
            'LD%',
            'GB%',
            'FB%',
            'IFFB%',
            'HR/FB',
            'IFH%',
            'BUH%',
            'Pull%',
            'Cent%',
            'Oppo%',
            'Soft%',
            'Med%',
            'Hard%',
            'TTO%',
            'LD%+',
            'GB%+',
            'FB%+',
            'HRFB%+',
            'Pull%+',
            'Cent%+',
            'Oppo%+',
            'Soft%+',
            'Med%+',
            'Hard%+',
            'BABIP+',

{%- endmacro -%}