{%- macro fangraphs_pitch_info_columns(stat) -%}

    {%- set columns = [
        {'raw_name': 'piFA%', 'column_name': 'four_seam_fastball_percentage_pi', 'type': 'numeric'},
        {'raw_name': 'piFC%', 'column_name': 'cutter_percentage_pi', 'type': 'numeric'},
        {'raw_name': 'piFS%', 'column_name': 'splitter_percentage_pi', 'type': 'numeric'},
        {'raw_name': 'piSI%', 'column_name': 'sinker_percentage_pi', 'type': 'numeric'},
        {'raw_name': 'piCH%', 'column_name': 'changeup_percentage_pi', 'type': 'numeric'},
        {'raw_name': 'piSL%', 'column_name': 'slider_percentage_pi', 'type': 'numeric'},
        {'raw_name': 'piCU%', 'column_name': 'curveball_percentage_pi', 'type': 'numeric'},
        {'raw_name': 'piCS%', 'column_name': 'slow_curveball_percentage_pi', 'type': 'numeric'},
        {'raw_name': 'piKN%', 'column_name': 'knuckleball_percentage_pi', 'type': 'numeric'},
        {'raw_name': 'piSB%', 'column_name': 'screwball_percentage_pi', 'type': 'numeric'},
        {'raw_name': 'piXX%', 'column_name': 'unidentified_pitch_percentage_pi', 'type': 'numeric'},
        {'raw_name': 'pivFA', 'column_name': 'four_seam_fastball_velocity_pi', 'type': 'numeric'},
        {'raw_name': 'pivFC', 'column_name': 'cutter_velocity_pi', 'type': 'numeric'},
        {'raw_name': 'pivFS', 'column_name': 'splitter_velocity_pi', 'type': 'numeric'},
        {'raw_name': 'pivSI', 'column_name': 'sinker_velocity_pi', 'type': 'numeric'},
        {'raw_name': 'pivCH', 'column_name': 'changeup_velocity_pi', 'type': 'numeric'},
        {'raw_name': 'pivSL', 'column_name': 'slider_velocity_pi', 'type': 'numeric'},
        {'raw_name': 'pivCU', 'column_name': 'curveball_velocity_pi', 'type': 'numeric'},
        {'raw_name': 'pivCS', 'column_name': 'slow_curveball_velocity_pi', 'type': 'numeric'},
        {'raw_name': 'pivKN', 'column_name': 'knuckleball_velocity_pi', 'type': 'numeric'},
        {'raw_name': 'pivSB', 'column_name': 'screwball_velocity_pi', 'type': 'numeric'},
        {'raw_name': 'pivXX', 'column_name': 'unidentified_pitch_velocity_pi', 'type': 'numeric'},
        {'raw_name': 'piFA-X', 'column_name': 'four_seam_fastball_horizontal_movement_pi', 'type': 'numeric'},
        {'raw_name': 'piFC-X', 'column_name': 'cutter_horizontal_movement_pi', 'type': 'numeric'},
        {'raw_name': 'piFS-X', 'column_name': 'splitter_horizontal_movement_pi', 'type': 'numeric'},
        {'raw_name': 'piSI-X', 'column_name': 'sinker_horizontal_movement_pi', 'type': 'numeric'},
        {'raw_name': 'piCH-X', 'column_name': 'changeup_horizontal_movement_pi', 'type': 'numeric'},
        {'raw_name': 'piSL-X', 'column_name': 'slider_horizontal_movement_pi', 'type': 'numeric'},
        {'raw_name': 'piCU-X', 'column_name': 'curveball_horizontal_movement_pi', 'type': 'numeric'},
        {'raw_name': 'piCS-X', 'column_name': 'slow_curveball_horizontal_movement_pi', 'type': 'numeric'},
        {'raw_name': 'piKN-X', 'column_name': 'knuckleball_horizontal_movement_pi', 'type': 'numeric'},
        {'raw_name': 'piSB-X', 'column_name': 'screwball_horizontal_movement_pi', 'type': 'numeric'},
        {'raw_name': 'piXX-X', 'column_name': 'unidentified_pitch_horizontal_movement_pi', 'type': 'numeric'},
        {'raw_name': 'piFA-Z', 'column_name':  'four_seam_fastball_vertical_movement_pi',  'type':  'numeric'},
        {'raw_name': 'piFC-Z',  'column_name':  'cutter_vertical_movement_pi',  'type':  'numeric'},
        {'raw_name': 'piFS-Z',  'column_name':  'splitter_vertical_movement_pi',  'type':  'numeric'},
        {'raw_name': 'piSI-Z',  'column_name':  'sinker_vertical_movement_pi',  'type':  'numeric'},
        {'raw_name': 'piCH-Z',  'column_name':  'changeup_vertical_movement_pi',  'type':  'numeric'},
        {'raw_name': 'piSL-Z',  'column_name':  'slider_vertical_movement_pi',  'type':  'numeric'},
        {'raw_name': 'piCU-Z',  'column_name':  'curveball_vertical_movement_pi',  'type':  'numeric'},
        {'raw_name': 'piCS-Z',  'column_name':  'slow_curveball_vertical_movement_pi',  'type':  'numeric'},
        {'raw_name': 'piKN-Z',  'column_name':  'knuckleball_vertical_movement_pi',  'type':  'numeric'},
        {'raw_name': 'piSB-Z',  'column_name':  'screwball_vertical_movement_pi',  'type':  'numeric'},
        {'raw_name': 'piXX-Z',  'column_name':  'unidentified_pitch_vertical_movement_pi',  'type':  'numeric'},
        {'raw_name': 'piwFA', 'column_name': 'four_seam_fastball_runs_above_average_pi', 'type': 'numeric'},
        {'raw_name': 'piwFC', 'column_name': 'cutter_runs_above_average_pi', 'type': 'numeric'},
        {'raw_name': 'piwFS', 'column_name': 'splitter_runs_above_average_pi', 'type': 'numeric'},
        {'raw_name': 'piwSI', 'column_name': 'sinker_runs_above_average_pi', 'type': 'numeric'},
        {'raw_name': 'piwCH', 'column_name': 'changeup_runs_above_average_pi', 'type': 'numeric'},
        {'raw_name': 'piwSL', 'column_name': 'slider_runs_above_average_pi', 'type': 'numeric'},
        {'raw_name': 'piwCU', 'column_name': 'curveball_runs_above_average_pi', 'type': 'numeric'},
        {'raw_name': 'piwCS', 'column_name': 'slow_curveball_runs_above_average_pi', 'type': 'numeric'},
        {'raw_name': 'piwKN', 'column_name': 'knuckleball_runs_above_average_pi', 'type': 'numeric'},
        {'raw_name': 'piwSB', 'column_name': 'screwball_runs_above_average_pi', 'type': 'numeric'},
        {'raw_name': 'piwXX', 'column_name': 'unidentified_pitch_runs_above_average_pi', 'type': 'numeric'},
        {'raw_name': 'piwFA/C',  'column_name':  'four_seam_fastball_runs_above_average_per_100_pitches_pi',  'type':  'numeric'},
        {'raw_name': 'piwFC/C',  'column_name':  'cutter_runs_above_average_per_100_pitches_pi',  'type':  'numeric'},
        {'raw_name': 'piwFS/C',  'column_name':  'splitter_runs_above_average_per_100_pitches_pi',  'type':  'numeric'},
        {'raw_name': 'piwSI/C',  'column_name':  'sinker_runs_above_average_per_100_pitches_pi',  'type':  'numeric'},
        {'raw_name': 'piwCH/C',  'column_name':  'changeup_runs_above_average_per_100_pitches_pi',  'type':  'numeric'},
        {'raw_name': 'piwSL/C',  'column_name':  'slider_runs_above_average_per_100_pitches_pi',  'type':  'numeric'},
        {'raw_name': 'piwCU/C',  'column_name':  'curveball_runs_above_average_per_100_pitches_pi',  'type':  'numeric'},
        {'raw_name': 'piwCS/C',  'column_name':  'slow_curveball_runs_above_average_per_100_pitches_pi',  'type':  'numeric'},
        {'raw_name': 'piwKN/C',  'column_name':  'knuckleball_runs_above_average_per_100_pitches_pi',  'type':  'numeric'},
        {'raw_name': 'piwSB/C',  'column_name':  'screwball_runs_above_average_per_100_pitches_pi',  'type':  'numeric'},
        {'raw_name': 'piwXX/C',  'column_name':  'unidentified_pitch_runs_above_average_per_100_pitches_pi',  'type':  'numeric'},
        {'raw_name': 'piSwing%',  'column_name': 'swing_percentage_pi',  'type':  'numeric'},
        {'raw_name': 'piO-Swing%',  'column_name': 'outside_zone_swing_percentage_pi',  'type':  'numeric'},
        {'raw_name': 'piZ-Swing%',  'column_name': 'inside_zone_swing_percentage_pi',  'type':  'numeric'},
        {'raw_name': 'piContact%',  'column_name': 'contact_percentage_pi',  'type':  'numeric'},
        {'raw_name': 'piO-Contact%',  'column_name': 'outside_zone_contact_percentage_pi',  'type':  'numeric'},
        {'raw_name': 'piZ-Contact%',  'column_name': 'inside_zone_contact_percentage_pi',  'type':  'numeric'},
        {'raw_name': 'piPace',  'column_name': 'average_time_between_pitches_seconds_pi',  'type':  'numeric'}
    ] -%}

    {{ return(columns) }}

{%- endmacro -%}
